"""Add relationships

Revision ID: 274d695b1736
Revises: 02bd23c5c5fd
Create Date: 2024-03-26 01:01:56.591803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274d695b1736'
down_revision = '02bd23c5c5fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
